### PR TITLE
Added to error catching and reporting for fasta and samplelist parser

### PR DESCRIPTION
**Pull request by vidalrmartinez**

### CODE REVIEW

**Comment by ZwFink** [comment]
Hi Vidal,
Can you add some tests for this new functionality, just to make sure that it throws an error exactly when it is expected to?

**Comment by ZwFink** [comment]
These look good, but I have a nitpick: it may be better to move the tests for samplelist_parser into a single TEST_CASE, and use SECTIONs for each of the existing test cases. This way the tests for the class are in a single place, as they are currently on nearly opposite ends of the file. 

It would look something like this: 
```c++
TEST_CASE( "samplelist_parser is able to read files that exist, properly creates errors when file cannot be found/read", "[samplelist_parser]"
{
    SECTION( "samplelist_parser is able to read a well-formed test" )
   {
         // original test goes here 
    }
  SECTION( "samplelist_parser throws when file is not found" )
   {
   }

}
```
and so on. This would be for both fasta_parser and samplelist_parser.

**Comment by vidalrmartinez** [comment]
> These look good, but I have a nitpick: it may be better to move the tests for samplelist_parser into a single TEST_CASE, and use SECTIONs for each of the existing test cases. This way the tests for the class are in a single place, as they are currently on nearly opposite ends of the file.
> 
> It would look something like this:
> 
> ```c++
> TEST_CASE( "samplelist_parser is able to read files that exist, properly creates errors when file cannot be found/read", "[samplelist_parser]"
> {
>     SECTION( "samplelist_parser is able to read a well-formed test" )
>    {
>          // original test goes here 
>     }
>   SECTION( "samplelist_parser throws when file is not found" )
>    {
>    }
> 
> }
> ```
> 
> and so on. This would be for both fasta_parser and samplelist_parser.

Of course! I can do that. I'll have that changed in a minute.

**Comment by ZwFink** [comment]
Don't forget to add a brief description of this change to the ```Unreleased``` section of the CHANGELOG

**Comment by ZwFink** [comment]
And to close this issue when merging it into the develop branch :)

**Pull request merged**
